exec-once = hyprpaper
exec-once = ~/scripts/archlights.sh
exec-once = waybar
exec-once = /home/kooller/.cargo/bin/noti run
exec-once = python3 -m http.server 1234 --directory /home/kooller/projects/newPageInteractive

exec-once = wl-clip-persist --clipboard both

exec-once = gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-mocha-lavender-standard+default"

#exec-once = openvpn --config ~/newconf.ovpn

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#exec-once = [workspace 1] flatpak run net.waterfox.waterfox
# exec-once = [workspace 9] kitty --title fastfetch -e zsh -i -c "ff; exec zsh"
# exec-once = [workspace 7] kitty --title btop -e btop
exec-once = [workspace 10] kitty --title hiddify -e zsh -i -c "sudo hiddify"

exec-once = [workspace 8] kitty --title calendar -e python3 ~/scripts/calendar.py
exec-once = [workspace 8] kitty --title stormy -e zsh -i -c "stormy; exec zsh"
exec-once = [workspace 8] kitty --title raspisanie -e zsh -i -c "~/scripts/raspisanie; exec zsh"

# exec-once = [workspace 6] kitty --title cava -e zsh -i -c "cava"
# exec-once = [workspace 6] kitty --title matrix -e ~/scripts/matrix
# exec-once = [workspace 6] kitty --title clock -e ~/scripts/ctermtime

# exec-once = [workspace 6] kitty --title cava -e zsh -i -c "cava"
# exec-once = [workspace 6] kitty --title matrix -e ~/scripts/matrix
# exec-once = [workspace 6] kitty --title clock -e zsh -i -c "run time; zsh"

exec-once = sleep 1 && hyprctl dispatch workspace 10

exec-once = xhost si:localuser:root

exec-once = [workspace special:telegram] Telegram
