windowrule = tile on, match:class ^kitty$

windowrule = float on, size 360 216, move 100 150, match:title ^(calendar)$
windowrule = float on, size 360 216, move 100 400, match:title ^(stormy)$
windowrule = float on, size 360 216, move 100 650, match:title ^(raspisanie)$

windowrule = float on, size 600 400, move 40 90, match:title ^matrix$
windowrule = float on, size 600 400, move 1920 90, match:title ^clock$

windowrule = workspace 1, match:class ^(waterfox-default)$

workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0

windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
windowrule = rounding 0, match:float 0, match:workspace f[1]

windowrule = suppress_event maximize, match:class .*

windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

windowrule = workspace special:telegram, float on, size 1600 1000, move 480 220, match:class ^(org.telegram.desktop)$

windowrule = no_blur on, opaque on, size (monitor_w) (monitor_h), decorate off, no_anim on, float on, pin on, match:class ^kando$

layerrule = blur on, match:namespace rofi
layerrule = blur_popups on, match:namespace rofi


windowrule = no_blur on, match:class ^raylib$
windowrule = no_shadow on, match:class ^raylib$
windowrule = border_size 0, match:class ^raylib$
windowrule = rounding 0, match:class ^raylib$
windowrule = decorate off, match:class ^raylib$
